// Trade-language aliases: map what a trader types to words that appear in
// official nomenclature descriptions. Each entry is a list of word-sets;
// a word-set matches when ALL its words appear in a description (union of sets).
export const ALIASES: Record<string, string[][]> = {
  'keychain': [['key', 'chain']],
  'keychains': [['key', 'chain']],
  'keychain ring': [['key', 'chain']],
  'key ring': [['key', 'chain']],
  'keyring': [['key', 'chain']],
  'key fob': [['key', 'chain']],
  'mobile phone': [['smartphones'], ['cellular', 'telephone']],
  'mobile phones': [['smartphones'], ['cellular', 'telephone']],
  'mobile': [['smartphones'], ['cellular', 'telephone']],
  'cell phone': [['smartphones'], ['cellular', 'telephone']],
  'cellphone': [['smartphones']],
  'phone': [['smartphones'], ['telephone']],
  'iphone': [['smartphones']],
  'led bulb': [['led', 'lamp']],
  'led bulbs': [['led', 'lamp']],
  'led light': [['led', 'lamp']],
  'led lights': [['led', 'lamp']],
  'lithium battery': [['lithium-ion'], ['lithium', 'accumulator'], ['lithium', 'batteries']],
  'lithium ion battery': [['lithium-ion'], ['lithium', 'accumulator']],
  'battery': [['batteries'], ['accumulator']],
  'batteries': [['batteries'], ['accumulator']],
  'sofa': [['seats']],
  'sofa set': [['seats']],
  'couch': [['seats']],
  'electric scooter': [['electric', 'motorcycle'], ['mopeds']],
  'e scooter': [['electric', 'motorcycle'], ['mopeds']],
  'scooter': [['motorcycles'], ['mopeds']],
  'bike': [['motorcycles'], ['bicycles']],
  'motorbike': [['motorcycles']],
  'air conditioner': [['air', 'conditioning']],
  'air conditioners': [['air', 'conditioning']],
  'ac unit': [['air', 'conditioning']],
  'fridge': [['refrigerator']],
  'refrigerator': [['refrigerator'], ['refrigerating']],
  'shoes': [['footwear']],
  'shoe': [['footwear']],
  'sneakers': [['footwear'], ['sports', 'footwear']],
  'chappal': [['footwear']],
  'slippers': [['footwear']],
  'medicine': [['medicaments']],
  'medicines': [['medicaments']],
  'tv': [['television', 'reception'], ['television']],
  'television': [['television', 'reception'], ['television']],
  'televisions': [['television', 'reception'], ['television']],
  'smart tv': [['television', 'reception'], ['television']],
  'led tv': [['television', 'reception'], ['television']],
  'earphones': [['headphones'], ['earphones']],
  'headphones': [['headphones']],
  'earbuds': [['headphones'], ['earphones']],
  'pen-drive': [['solid-state', 'storage']],
  'tshirt': [['t-shirts']],
  't shirt': [['t-shirts']],
  't-shirt': [['t-shirts']],
  'saree': [['sarees'], ['silk', 'fabrics']],
  'gold chain': [['jewellery', 'gold']],
  'gold ring': [['jewellery', 'gold']],
  'silver jewellery': [['jewellery', 'silver']],
  'attar': [['essential', 'oils']],
  'perfume': [['perfumes']],
  'aata': [['wheat', 'flour']],
  'atta': [['wheat', 'flour']],
  'dal': [['pulses'], ['lentils']],
  'pulses': [['pulses'], ['leguminous']],
  'ghee': [['ghee'], ['butter']],
  'paneer': [['cheese']],
  'masala': [['mixtures', 'spices'], ['spices']],
  'jewellery': [['jewellery']],
  'jewelry': [['jewellery']],
  'sugar': [['cane', 'beet'], ['cane', 'sugar'], ['beet', 'sugar'], ['sugar']],
  'tyre': [['new', 'pneumatic', 'tyres'], ['tyres']],
  'tire': [['new', 'pneumatic', 'tyres'], ['tyres']],
  'toys': [['toys']],
  'diesel': [['diesel', 'oil'], ['diesel', 'fuel'], ['gas', 'oil'], ['diesel']],
  'diesel oil': [['diesel', 'oil'], ['diesel']],
  'laptop battery': [['lithium-ion'], ['lithium', 'accumulator'], ['battery']],
  'laptop': [['portable', 'automatic', 'data'], ['laptop']],
  'laptops': [['portable', 'automatic', 'data'], ['laptop']],
  'hsd': [['high', 'speed', 'diesel'], ['diesel']],
  'hsd oil': [['high', 'speed', 'diesel'], ['diesel']],
  'high speed diesel': [['high', 'speed', 'diesel'], ['diesel']],
  'lpg': [['liquefied', 'petroleum', 'gas']],
  'lpg gas': [['liquefied', 'petroleum', 'gas']],
  'ms': [['motor', 'spirit'], ['mild', 'steel']],
  'motor spirit': [['motor', 'spirit'], ['gasoline']],
  'petrol': [['motor', 'spirit'], ['gasoline']],
  'atf': [['aviation', 'turbine', 'fuel'], ['jet', 'fuel']],
  'jet fuel': [['aviation', 'turbine', 'fuel'], ['jet', 'fuel'], ['kerosene']],
  'cng': [['compressed', 'natural', 'gas'], ['natural', 'gas']],
  'png': [['natural', 'gas']],
  'furnace oil': [['furnace', 'oil'], ['fuel', 'oils']],
  'fo': [['furnace', 'oil'], ['fuel', 'oils']],
  'pvc': [['polymers', 'vinyl', 'chloride', 'primary'], ['polyvinyl', 'chloride']],
  'hdpe': [['high', 'density', 'polyethylene'], ['polyethylene', '0.94']],
  'ldpe': [['low', 'density', 'polyethylene']],
  'pp': [['polypropylene'], ['propylene', 'polymer']],
  'pet': [['polyethylene', 'terephthalate']],
  'abs': [['acrylonitrile', 'butadiene', 'styrene']],
  'tmt': [['bars', 'reinforcing'], ['bars', 'rods', 'hot-rolled']],
  'tmt bar': [['bars', 'reinforcing'], ['bars', 'rods', 'hot-rolled']],
  'tmt bars': [['bars', 'reinforcing'], ['bars', 'rods', 'hot-rolled']],
  'gi': [['galvanised'], ['galvanized'], ['coated', 'zinc'], ['plated', 'zinc']],
  'gi sheet': [['galvanised'], ['galvanized'], ['coated', 'zinc'], ['plated', 'zinc']],
  'ev': [['electric', 'propulsion'], ['electric', 'vehicle']],
  'electric vehicle': [['electric', 'propulsion'], ['electric', 'vehicle']],
  'solar panel': [['photovoltaic'], ['solar', 'cells']],
  'solar panels': [['photovoltaic'], ['solar', 'cells']],
  'solar cell': [['photovoltaic'], ['solar', 'cells']],
  'solar cells': [['photovoltaic'], ['solar', 'cells']],
  'pen drive': [['solid', 'state']],
  'pen drives': [['solid', 'state']],
  'pendrive': [['solid', 'state']],
  'pendrives': [['solid', 'state']],
  'usb drive': [['solid', 'state']],
  'usb drives': [['solid', 'state']],
  'usb stick': [['solid', 'state']],
  'usb flash drive': [['solid', 'state']],
  'flash drive': [['solid', 'state']],
  'flash drives': [['solid', 'state']],
  'thumb drive': [['solid', 'state']],
  'thumb drives': [['solid', 'state']],
  'memory stick': [['solid', 'state']],
  'memory card': [['solid', 'state']],
  'memory cards': [['solid', 'state']],
  'mobile charger': [['battery', 'chargers']],
  'phone charger': [['battery', 'chargers']],
  'chargers': [['battery', 'chargers']],
  'usb cable': [['fitted', 'connectors']],
  'usb cables': [['fitted', 'connectors']],
  'usb cord': [['fitted', 'connectors']],
  'charging cable': [['fitted', 'connectors']],
  'data cable': [['fitted', 'connectors']],
  'power bank': [['lithium', 'accumulator']],
  'power banks': [['lithium', 'accumulator']],
  'powerbank': [['lithium', 'accumulator']],
  'bluetooth speaker': [['loudspeakers']],
  'bluetooth speakers': [['loudspeakers']],
  'wireless speaker': [['loudspeakers']],
  'wireless speakers': [['loudspeakers']],
  'smart speaker': [['loudspeakers']],
  'jeans': [['trousers', 'cotton'], ['denim', 'trousers']],
  'denim jeans': [['trousers', 'cotton'], ['denim', 'trousers']],
  'blue jeans': [['trousers', 'cotton'], ['denim', 'trousers']],
  'keyboard': [['input', 'output']],
  'keyboards': [['input', 'output']],
  'computer keyboard': [['input', 'output']],
  'basmati rice': [['rice'],['wholly','milled']],
  'black tea': [['tea'],['fermented','tea']],
  'cardamom': [['cardamoms'],['spices']],
  'turmeric': [['turmeric'],['curcuma']],
  'ceiling fan': [['fans'],['electric','fans']],
  'ceramic tiles': [['ceramic','tiles'],['flagstones']],
  'microwave oven': [['microwave','ovens']],
  'washing machine': [['washing','machines'],['household','laundry']],
  'water purifier': [['filtering','machinery'],['purifying','water']],
  'bicycle': [['bicycles'],['cycles','not','motorised']],
  'granite slab': [['granite'],['monumental','stone']],
  'marble': [['marble'],['travertine']],
  'portland cement': [['portland','cement'],['hydraulic','cements']],
  'urea': [['urea'],['mineral','fertilisers']],
  'raw cotton': [['cotton','not','carded'],['cotton','fibres']],
  'leather handbag': [['handbags'],['composition','leather']],
  'cashew nuts': [['cashew','nuts'],['edible','nuts']],
  'almonds': [['almonds'],['nuts','fresh']],
  'mustard oil': [['mustard','oil'],['colza','oil']],
  'crude palm oil': [['palm','oil'],['crude','oil']],
  'ethanol': [['ethyl','alcohol'],['denatured','spirits']],
  'stainless steel pipes': [['tubes','pipes'],['stainless','steel']],
  'copper wire': [['copper','wire'],['refined','copper']],
  'aluminium ingots': [['unwrought','aluminium'],['aluminium','ingots']],
  'a4 paper': [['uncoated','paper'],['writing','paper']],
  'bedsheet': [['bed','linen'],['toilet','linen']],
  'shampoo': [['shampoos'],['hair','preparations']],
  'toilet soap': [['soap']],
  'toothpaste': [['dentifrices'],['oral','hygiene']],
  'sunglasses': [['sunglasses'],['spectacles','corrective']],
  'cctv camera': [['television','cameras'],['digital','cameras']],
  'power inverter': [['static','converters'],['inverters']],
  'safety helmet': [['safety','headgear'],['headgear']],
  'sanitary napkin': [['sanitary','towels'],['tampons']],
  'baby diaper': [['napkins','babies'],['diaper','liners']],
  'electric motor': [['electric','motors'],['generators']],
  'cumin seeds': [['cumin']],
  'jeera': [['cumin','seeds'],['cumin']],
  'fresh onions': [['onions']],
  'pyaz': [['onions','fresh'],['shallots']],
  'ginger': [['ginger']],
  'garlic': [['garlic']],
  'cloves': [['cloves'],['whole','fruit']],
  'black pepper': [['pepper'],['piper']],
  'soybean oil': [['crude','oil']],
  'sunflower oil': [['safflower','oil']],
  'kurti': [['dresses'],['blouses','shirts']],
  'tracksuit': [['track','suits'],['ski','suits']],
  'tablet pc': [['portable','automatic','data'],['processing','machines']],
  'laser printer': [['printers'],['printing','machinery']],
  'optical fiber cable': [['optical','fibres'],['optical','fiber','cables']],
  'printed circuit board': [['printed','circuits']],
  'umbrella': [['umbrellas'],['sun','umbrellas']],
  'wrist watch': [['clocks','and','watches']],
  'mattress': [['mattresses'],['mattress','supports']],
  'blanket': [['blankets'],['travelling','rugs']],
  'curtains': [['curtains'],['interior','blinds']],
  'bath towel': [['toilet','linen'],['towels']],
  'surgical mask': [['face','masks'],['appliances']],
  'latex gloves': [['gloves','mittens'],['surgical','gloves']],
  'digital thermometer': [['thermometers'],['pyrometers']],
  'ballpoint pen': [['ball','point','pens'],['ballpoint']],
  'exercise notebook': [['exercise','books'],['notebooks']],
  'corrugated box': [['cartons','boxes'],['corrugated','paper']],
  'trolley bag': [['trunks']],
  'backpack': [['rucksacks'],['sports','bags']],
  'coffee beans': [['coffee','whether','roasted'],['not','roasted']],
  'natural honey': [['natural','honey']],
  'raisins': [['grapes','dried'],['raisins']],
  'padlock': [['padlocks'],['locks','used','for']],
};
