// Trade-language aliases: map what a trader types to words that appear in
// official nomenclature descriptions. Each entry is a list of word-sets;
// a word-set matches when ALL its words appear in a description (union of sets).
export const ALIASES: Record<string, string[][]> = {
  'mobile phone': [['smartphones'], ['cellular', 'telephone']],
  'mobile phones': [['smartphones'], ['cellular', 'telephone']],
  'mobile': [['smartphones'], ['cellular', 'telephone']],
  'cell phone': [['smartphones'], ['cellular', 'telephone']],
  'cellphone': [['smartphones']],
  'phone': [['smartphones'], ['telephone']],
  'iphone': [['smartphones']],
  'led bulb': [['led', 'lamp']],
  'led bulbs': [['led', 'lamp']],
  'led light': [['led', 'lamp']],
  'led lights': [['led', 'lamp']],
  'lithium battery': [['lithium-ion'], ['lithium', 'accumulator'], ['lithium', 'batteries']],
  'lithium ion battery': [['lithium-ion'], ['lithium', 'accumulator']],
  'battery': [['batteries'], ['accumulator']],
  'batteries': [['batteries'], ['accumulator']],
  'sofa': [['seats']],
  'sofa set': [['seats']],
  'couch': [['seats']],
  'electric scooter': [['electric', 'motorcycle'], ['mopeds']],
  'e scooter': [['electric', 'motorcycle'], ['mopeds']],
  'scooter': [['motorcycles'], ['mopeds']],
  'bike': [['motorcycles'], ['bicycles']],
  'motorbike': [['motorcycles']],
  'air conditioner': [['air', 'conditioning']],
  'air conditioners': [['air', 'conditioning']],
  'ac unit': [['air', 'conditioning']],
  'fridge': [['refrigerator']],
  'refrigerator': [['refrigerator'], ['refrigerating']],
  'shoes': [['footwear']],
  'shoe': [['footwear']],
  'sneakers': [['footwear'], ['sports', 'footwear']],
  'chappal': [['footwear']],
  'slippers': [['footwear']],
  'medicine': [['medicaments']],
  'medicines': [['medicaments']],
  'tv': [['television']],
  'television': [['television']],
  'earphones': [['headphones'], ['earphones']],
  'headphones': [['headphones']],
  'earbuds': [['headphones'], ['earphones']],
  'pen drive': [['solid-state', 'storage'], ['usb', 'storage']],
  'pen-drive': [['solid-state', 'storage']],
  'tshirt': [['t-shirts']],
  't shirt': [['t-shirts']],
  't-shirt': [['t-shirts']],
  'jeans': [['denim'], ['jeans']],
  'saree': [['sarees'], ['silk', 'fabrics']],
  'gold chain': [['jewellery', 'gold']],
  'gold ring': [['jewellery', 'gold']],
  'silver jewellery': [['jewellery', 'silver']],
  'attar': [['essential', 'oils']],
  'perfume': [['perfumes']],
  'aata': [['wheat', 'flour']],
  'atta': [['wheat', 'flour']],
  'dal': [['pulses'], ['lentils']],
  'pulses': [['pulses'], ['leguminous']],
  'ghee': [['ghee'], ['butter']],
  'paneer': [['cheese']],
  'masala': [['mixtures', 'spices'], ['spices']],
  'jewellery': [['jewellery']],
  'jewelry': [['jewellery']],
  'tyre': [['tyres']],
  'tire': [['tyres']],
  'toys': [['toys']],
};
