// Trade-language aliases: map what a trader types to words that appear in
// official nomenclature descriptions. Each entry is a list of word-sets;
// a word-set matches when ALL its words appear in a description (union of sets).
export const ALIASES: Record<string, string[][]> = {
  'mobile phone': [['smartphones'], ['cellular', 'telephone']],
  'mobile phones': [['smartphones'], ['cellular', 'telephone']],
  'mobile': [['smartphones'], ['cellular', 'telephone']],
  'cell phone': [['smartphones'], ['cellular', 'telephone']],
  'cellphone': [['smartphones']],
  'phone': [['smartphones'], ['telephone']],
  'iphone': [['smartphones']],
  'led bulb': [['led', 'lamp']],
  'led bulbs': [['led', 'lamp']],
  'led light': [['led', 'lamp']],
  'led lights': [['led', 'lamp']],
  'lithium battery': [['lithium-ion'], ['lithium', 'accumulator'], ['lithium', 'batteries']],
  'lithium ion battery': [['lithium-ion'], ['lithium', 'accumulator']],
  'battery': [['batteries'], ['accumulator']],
  'batteries': [['batteries'], ['accumulator']],
  'sofa': [['seats']],
  'sofa set': [['seats']],
  'couch': [['seats']],
  'electric scooter': [['electric', 'motorcycle'], ['mopeds']],
  'e scooter': [['electric', 'motorcycle'], ['mopeds']],
  'scooter': [['motorcycles'], ['mopeds']],
  'bike': [['motorcycles'], ['bicycles']],
  'motorbike': [['motorcycles']],
  'air conditioner': [['air', 'conditioning']],
  'air conditioners': [['air', 'conditioning']],
  'ac unit': [['air', 'conditioning']],
  'fridge': [['refrigerator']],
  'refrigerator': [['refrigerator'], ['refrigerating']],
  'shoes': [['footwear']],
  'shoe': [['footwear']],
  'sneakers': [['footwear'], ['sports', 'footwear']],
  'chappal': [['footwear']],
  'slippers': [['footwear']],
  'medicine': [['medicaments']],
  'medicines': [['medicaments']],
  'tv': [['television']],
  'television': [['television']],
  'earphones': [['headphones'], ['earphones']],
  'headphones': [['headphones']],
  'earbuds': [['headphones'], ['earphones']],
  'pen drive': [['solid-state', 'storage'], ['usb', 'storage']],
  'pen-drive': [['solid-state', 'storage']],
  'tshirt': [['t-shirts']],
  't shirt': [['t-shirts']],
  't-shirt': [['t-shirts']],
  'jeans': [['denim'], ['jeans']],
  'saree': [['sarees'], ['silk', 'fabrics']],
  'gold chain': [['jewellery', 'gold']],
  'gold ring': [['jewellery', 'gold']],
  'silver jewellery': [['jewellery', 'silver']],
  'attar': [['essential', 'oils']],
  'perfume': [['perfumes']],
  'aata': [['wheat', 'flour']],
  'atta': [['wheat', 'flour']],
  'dal': [['pulses'], ['lentils']],
  'pulses': [['pulses'], ['leguminous']],
  'ghee': [['ghee'], ['butter']],
  'paneer': [['cheese']],
  'masala': [['mixtures', 'spices'], ['spices']],
  'jewellery': [['jewellery']],
  'jewelry': [['jewellery']],
  'sugar': [['cane', 'beet'], ['cane', 'sugar'], ['beet', 'sugar'], ['sugar']],
  'tyre': [['new', 'pneumatic', 'tyres'], ['tyres']],
  'tire': [['new', 'pneumatic', 'tyres'], ['tyres']],
  'toys': [['toys']],
  'hsd': [['high', 'speed', 'diesel'], ['diesel']],
  'hsd oil': [['high', 'speed', 'diesel'], ['diesel']],
  'high speed diesel': [['high', 'speed', 'diesel'], ['diesel']],
  'lpg': [['liquefied', 'petroleum', 'gas']],
  'lpg gas': [['liquefied', 'petroleum', 'gas']],
  'ms': [['motor', 'spirit'], ['mild', 'steel']],
  'motor spirit': [['motor', 'spirit'], ['gasoline']],
  'petrol': [['motor', 'spirit'], ['gasoline']],
  'atf': [['aviation', 'turbine', 'fuel'], ['jet', 'fuel']],
  'jet fuel': [['aviation', 'turbine', 'fuel'], ['jet', 'fuel'], ['kerosene']],
  'cng': [['compressed', 'natural', 'gas'], ['natural', 'gas']],
  'png': [['natural', 'gas']],
  'furnace oil': [['furnace', 'oil'], ['fuel', 'oils']],
  'fo': [['furnace', 'oil'], ['fuel', 'oils']],
  'pvc': [['polymers', 'vinyl', 'chloride', 'primary'], ['polyvinyl', 'chloride']],
  'hdpe': [['high', 'density', 'polyethylene'], ['polyethylene', '0.94']],
  'ldpe': [['low', 'density', 'polyethylene']],
  'pp': [['polypropylene'], ['propylene', 'polymer']],
  'pet': [['polyethylene', 'terephthalate']],
  'abs': [['acrylonitrile', 'butadiene', 'styrene']],
  'tmt': [['bars', 'reinforcing'], ['bars', 'rods', 'hot-rolled']],
  'tmt bar': [['bars', 'reinforcing'], ['bars', 'rods', 'hot-rolled']],
  'tmt bars': [['bars', 'reinforcing'], ['bars', 'rods', 'hot-rolled']],
  'gi': [['galvanised'], ['galvanized'], ['coated', 'zinc'], ['plated', 'zinc']],
  'gi sheet': [['galvanised'], ['galvanized'], ['coated', 'zinc'], ['plated', 'zinc']],
  'ev': [['electric', 'propulsion'], ['electric', 'vehicle']],
  'electric vehicle': [['electric', 'propulsion'], ['electric', 'vehicle']],
  'solar panel': [['photovoltaic'], ['solar', 'cells']],
  'solar panels': [['photovoltaic'], ['solar', 'cells']],
  'solar cell': [['photovoltaic'], ['solar', 'cells']],
  'solar cells': [['photovoltaic'], ['solar', 'cells']],
};
